# Site settings
title: Sagar Gandhi
meta_description: Blog
baseurl: "" # Subpath, e.g. /blog/
url: "http://www.sagargandhi.com" # Base protocol and hostname
paginate: 5 # How many posts to show per page

# External Pages
#external_pages:
# - title: Themeforest
#   url: https://www.themeforest.net

#gems
gems: [jekyll-paginate]

# Google Analytics
google_analytics: UA-56071882-1

# Author settings
author_name: Sagar Gandhi
author_description: Modern Age Researcher
author_image: /images/avtar.png
author_image_width: 480
author_image_height: 480
author_image_mime: image/png

# Share settings
share_buttons: on

# Comments settings
disqus_shortname: sagar-gandhi

# Sidebar settings
sidebar: left # left|right
social_widget: on
subscribe_widget: off
copyright_notice: on

# Social settings
github_username : Gandhi-Sagar
linkedin_username : gandhisagar5
twitter_username : _sagar_gs
youtube_username : UCNsMfUTIg9CETvSTj1FMJDw
facebook_username : gandhi.techie
stackoverflow_username : 1256369/adorn

# Mailchimp.com - Email subscribtion settings
# Refer to http://kb.mailchimp.com/lists/signup-forms/advanced-form-customization
# form_action: "//tylercubell.us11.list-manage.com/subscribe/post?u=25ec516894b013df92dca1a8d&amp;id=8906705de6"
# list_id: "b_25ec516894b013df92dca1a8d_8906705de6"

# Formspreee.io - Contact form settings
# Note: submit form once to activate
email: gandhi.sagar.gs@gmail.com

# Build settings
markdown: kramdown

# Error Adjustment Settings
excerpt_separator: ""

# Sass settings
sass:
    style: :compressed
